alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias sf='php app/console'
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias py="python"
alias rn="react-native"
